spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: db_movie
  main:
    allow-bean-definition-overriding: true

countriesApi:
  url: https://restcountries.com/v3.1/

